import isnil from "lodash.isnil";
import isequal from "lodash.isequal";
import isnumber from "lodash.isnumber";
import isstring from "lodash.isstring";
import isdate from "lodash.isdate";
import padstart from "lodash.padstart";
import isnan from "lodash.isnan";
import isarray from "lodash.isarray";
import isboolean from "lodash.isboolean";
import isobject from "lodash.isobject";
import upperfirst from "lodash.upperfirst";
import camelcase from "lodash.camelcase";
import lowercase from "lodash.lowercase";
import trimLodash from "lodash.trim";
import capitalizeLodash from "lodash.capitalize";
import roundLodash from "lodash.round";

export const isNil = isnil;
export const isEqual = isequal;
export const isNumber = isnumber;
export const isString = isstring;
export const isDate = isdate;
export const padStart = padstart;
export const isNaN = isnan;
export const isArray = isarray;
export const isBoolean = isboolean;
export const isObject = isobject;
export const upperFirst = upperfirst;
export const camelCase = camelcase;
export const lowerCase = lowercase;
export const trim = trimLodash;
export const capitalize = capitalizeLodash;
export const round = roundLodash;
